FROM ubuntu:jammy
HEALTHCHECK --interval=30s --timeout=5s CMD echo "Hello World" || exit 1

LABEL "author"="Luca Capanna"
LABEL "licenze"="MIT License"
LABEL "image.version"="1.0.42024-test"
LABEL "image.name"="lukecottage/ops-image"
LABEL "env"="test"
LABEL "application"="sonar-scanner"
LABEL "scope"="test to install sonar-scanner"

USER root

# Hashicorp Args
ARG HASHICORP_APT_REPOSITORY=https://apt.releases.hashicorp.com
ARG HASHICORP_APT_PUBKEY=https://apt.releases.hashicorp.com/gpg

# System envs
ENV PATH="${PATH}:${HASHICORP_HOME}/bin"

# Workout TZ database setup
ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /opt
RUN mkdir -p /opt/scripts
COPY ./scripts/* /opt/scripts/
RUN chmod a+x /opt/scripts/*

# Update APT cache befor start install scripts
RUN apt-get update

# Install Hashicorp Tools CLI
RUN /opt/scripts/install_hashicorp-tools.sh --apt-url=${HASHICORP_APT_REPOSITORY} --gpg-url=${HASHICORP_APT_PUBKEY}

# Create OPS user and workspace
RUN yes Y | apt-get -y install sudo
RUN useradd -rm -d /home/operator -s /bin/bash -g root -G sudo -u 1042 operator
RUN mkdir -p /workspace && chown operator -R /workspace

# Cleanup and setup operator user/workspace
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN echo "operator ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER operator
WORKDIR /workspace
RUN terraform -help
RUN packer --help

CMD ["/bin/bash"]